// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/testt_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/testt_service.go -destination=internal/mock/service/mock_testt_service.go -package=mock_service
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	dto "github.com/hadi-projects/go-react-starter/internal/dto"
	dto0 "github.com/hadi-projects/go-react-starter/internal/dto/default"
	gomock "go.uber.org/mock/gomock"
)

// MockTesttService is a mock of TesttService interface.
type MockTesttService struct {
	ctrl     *gomock.Controller
	recorder *MockTesttServiceMockRecorder
	isgomock struct{}
}

// MockTesttServiceMockRecorder is the mock recorder for MockTesttService.
type MockTesttServiceMockRecorder struct {
	mock *MockTesttService
}

// NewMockTesttService creates a new mock instance.
func NewMockTesttService(ctrl *gomock.Controller) *MockTesttService {
	mock := &MockTesttService{ctrl: ctrl}
	mock.recorder = &MockTesttServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTesttService) EXPECT() *MockTesttServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTesttService) Create(req dto.CreateTesttRequest) (*dto.TesttResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*dto.TesttResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTesttServiceMockRecorder) Create(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTesttService)(nil).Create), req)
}

// Delete mocks base method.
func (m *MockTesttService) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTesttServiceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTesttService)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockTesttService) GetAll(pagination *dto0.PaginationRequest) (*dto0.PaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", pagination)
	ret0, _ := ret[0].(*dto0.PaginationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTesttServiceMockRecorder) GetAll(pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTesttService)(nil).GetAll), pagination)
}

// GetByID mocks base method.
func (m *MockTesttService) GetByID(id uint) (*dto.TesttResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*dto.TesttResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTesttServiceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTesttService)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockTesttService) Update(id uint, req dto.UpdateTesttRequest) (*dto.TesttResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, req)
	ret0, _ := ret[0].(*dto.TesttResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTesttServiceMockRecorder) Update(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTesttService)(nil).Update), id, req)
}
