// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/popo_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/popo_service.go -destination=internal/mock/service/mock_popo_service.go -package=mock_service
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	dto "github.com/hadi-projects/go-react-starter/internal/dto"
	dto0 "github.com/hadi-projects/go-react-starter/internal/dto/default"
	gomock "go.uber.org/mock/gomock"
)

// MockPopoService is a mock of PopoService interface.
type MockPopoService struct {
	ctrl     *gomock.Controller
	recorder *MockPopoServiceMockRecorder
	isgomock struct{}
}

// MockPopoServiceMockRecorder is the mock recorder for MockPopoService.
type MockPopoServiceMockRecorder struct {
	mock *MockPopoService
}

// NewMockPopoService creates a new mock instance.
func NewMockPopoService(ctrl *gomock.Controller) *MockPopoService {
	mock := &MockPopoService{ctrl: ctrl}
	mock.recorder = &MockPopoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPopoService) EXPECT() *MockPopoServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPopoService) Create(req dto.CreatePopoRequest) (*dto.PopoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*dto.PopoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPopoServiceMockRecorder) Create(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPopoService)(nil).Create), req)
}

// Delete mocks base method.
func (m *MockPopoService) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPopoServiceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPopoService)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockPopoService) GetAll(pagination *dto0.PaginationRequest) (*dto0.PaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", pagination)
	ret0, _ := ret[0].(*dto0.PaginationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPopoServiceMockRecorder) GetAll(pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPopoService)(nil).GetAll), pagination)
}

// GetByID mocks base method.
func (m *MockPopoService) GetByID(id uint) (*dto.PopoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*dto.PopoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPopoServiceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPopoService)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockPopoService) Update(id uint, req dto.UpdatePopoRequest) (*dto.PopoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, req)
	ret0, _ := ret[0].(*dto.PopoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPopoServiceMockRecorder) Update(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPopoService)(nil).Update), id, req)
}
