// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/testt_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/testt_repository.go -destination=internal/mock/repository/mock_testt_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	dto "github.com/hadi-projects/go-react-starter/internal/dto/default"
	entity "github.com/hadi-projects/go-react-starter/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTesttRepository is a mock of TesttRepository interface.
type MockTesttRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTesttRepositoryMockRecorder
	isgomock struct{}
}

// MockTesttRepositoryMockRecorder is the mock recorder for MockTesttRepository.
type MockTesttRepositoryMockRecorder struct {
	mock *MockTesttRepository
}

// NewMockTesttRepository creates a new mock instance.
func NewMockTesttRepository(ctrl *gomock.Controller) *MockTesttRepository {
	mock := &MockTesttRepository{ctrl: ctrl}
	mock.recorder = &MockTesttRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTesttRepository) EXPECT() *MockTesttRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTesttRepository) Create(arg0 *entity.Testt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTesttRepositoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTesttRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockTesttRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTesttRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTesttRepository)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockTesttRepository) FindAll(pagination *dto.PaginationRequest) ([]entity.Testt, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", pagination)
	ret0, _ := ret[0].([]entity.Testt)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockTesttRepositoryMockRecorder) FindAll(pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockTesttRepository)(nil).FindAll), pagination)
}

// FindByID mocks base method.
func (m *MockTesttRepository) FindByID(id uint) (*entity.Testt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.Testt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTesttRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTesttRepository)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockTesttRepository) Update(arg0 *entity.Testt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTesttRepositoryMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTesttRepository)(nil).Update), arg0)
}
