// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/popo_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/popo_repository.go -destination=internal/mock/repository/mock_popo_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	dto "github.com/hadi-projects/go-react-starter/internal/dto/default"
	entity "github.com/hadi-projects/go-react-starter/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPopoRepository is a mock of PopoRepository interface.
type MockPopoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPopoRepositoryMockRecorder
	isgomock struct{}
}

// MockPopoRepositoryMockRecorder is the mock recorder for MockPopoRepository.
type MockPopoRepositoryMockRecorder struct {
	mock *MockPopoRepository
}

// NewMockPopoRepository creates a new mock instance.
func NewMockPopoRepository(ctrl *gomock.Controller) *MockPopoRepository {
	mock := &MockPopoRepository{ctrl: ctrl}
	mock.recorder = &MockPopoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPopoRepository) EXPECT() *MockPopoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPopoRepository) Create(arg0 *entity.Popo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPopoRepositoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPopoRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockPopoRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPopoRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPopoRepository)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockPopoRepository) FindAll(pagination *dto.PaginationRequest) ([]entity.Popo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", pagination)
	ret0, _ := ret[0].([]entity.Popo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPopoRepositoryMockRecorder) FindAll(pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPopoRepository)(nil).FindAll), pagination)
}

// FindByID mocks base method.
func (m *MockPopoRepository) FindByID(id uint) (*entity.Popo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.Popo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPopoRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPopoRepository)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockPopoRepository) Update(arg0 *entity.Popo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPopoRepositoryMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPopoRepository)(nil).Update), arg0)
}
